#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

test_one() {
  printf "%s" "testing $1... "
  "$DIR"/xpy "$1" || exit 1
}

if [ $# -eq 0 ]; then
  for test in "$DIR/lib/"*; do
    test_one "$test"
  done
else
  test_one "$DIR/lib/$1"
fi
